### ISSUE TITLE
C support

### ISSUE THREAD

**Issue by kkanungo17** [balanceiskey/vim-framer-syntax#1]
Hi,

Would it be possible to add syntax colors for C and C++ syntax?

**Comment by sagar-barapatre** [comment]
Yeah Sure! But you have to use IDE such as VSCode or Sublime Text 3.0. These IDE's are pretty good when we want to check whether if we put proper parenthesis by showing with different colors. So I think it would a pretty good option to shift in either of these IDE's to experience good coding environment.
Happy Coding!!!!

**Comment by balanceiskey** [comment]
Hey @kkanungo17 I think we can do that! Sorry, I'm just checking back on this repo after a long, long while. Do you have a reference C file you might point me at? I can look at getting some starting points in there.

**Comment by balanceiskey** [comment]
@kkanungo17 Have another look if you come back to this repo, I think C should be lookin' at least a little better.

**Comment by balanceiskey** [comment]
Closin' it for now, but hit me up if it looks off, thanks!
